apiVersion: apps/v1
kind: Deployment
metadata:
  name: unhealthy-app
spec:
  replicas: 2
  selector:
    matchLabels: { app: unhealthy-app }
  template:
    metadata:
      labels: { app: unhealthy-app }
    spec:
      containers:
        - name: api
          image: eduardkh/unhealthy-app:latest
          ports: [{ containerPort: 8080 }]
          readinessProbe:
            httpGet: { path: /readyz, port: 8080 }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            periodSeconds: 10
