# This rule is not used by the project event-logger-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to monitor.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: event-logger-operator
    app.kubernetes.io/managed-by: kustomize
  name: eventlogger-viewer-role
rules:
- apiGroups:
  - monitor.example.com
  resources:
  - eventloggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitor.example.com
  resources:
  - eventloggers/status
  verbs:
  - get
