---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - monitor.example.com
  resources:
  - eventloggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.example.com
  resources:
  - eventloggers/finalizers
  verbs:
  - update
- apiGroups:
  - monitor.example.com
  resources:
  - eventloggers/status
  verbs:
  - get
  - patch
  - update
