// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import ()

type Todo struct {
	ID        int32  `json:"id"`
	Task      string `json:"task"`
	Completed bool   `json:"completed"`
}
