apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-logger-operator-controller-manager
  namespace: event-logger-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - name: manager
        image: eduardkh/event-logger-operator:v0.1.0
        command:
        - /manager
        args:
        - --leader-elect
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
